name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-gh-pages:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: git commit
        run: |
          cd ./dist
          git init
          git config user.email "github-action@huww98.cn"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Build"

          cd -
          git remote add dist ./dist
          git fetch dist
          git push -f origin refs/remotes/dist/master:refs/heads/gh-pages
